name: Flow Festival cms to s3 upload workflow

on:
  repository_dispatch:
    types:
      - webhook

jobs:
  s3_webhook:
    runs-on: ubuntu-latest
    outputs:
      deployment_target: ${{steps.s3_webhook_payload.outputs.deployment_target}}
    steps:
      - name: Incoming event from a webhook
        id: s3_webhook_payload
        run: |
          echo "deployment_target=${{ github.event.client_payload.deployment_target }}" >> $GITHUB_OUTPUT
  s3_tasks_in_staging:
    needs: s3_webhook
    runs-on: ubuntu-latest
    if: needs.s3_webhook.outputs.deployment_target == 'staging'
    steps:
      - name: scaffold s3 updates in staging
        run: echo 'scaffold s3 updates in staging'
  s3_tasks_in_prod:
    needs: s3_webhook
    runs-on: ubuntu-latest
    if: needs.s3_webhook.outputs.deployment_target == 'prod'
    steps:
      - name: scaffold s3 updates in staging
        run: echo 'scaffold s3 updates in prod'
