name: Actions bootcamp

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Incoming event from a webhook
        run: |
          echo "event name: $GITHUB_EVENT_NAME"
