name: Actions bootcamp

on: workflow_dispatch

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: |
          echo "Hello, World!" > hello.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: hello.txt
  bye:
    needs: hello
    runs-on: ubuntu-latest
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v4
        with:
          name: output
      - name: Read artifact
        run: cat hello.txt

      - name: Say Goodbye
        run: echo "Goodbye"
